name: CD with Maven

on:
  push:
    branches: [ "staging", "production" ]
  pull_request:
    branches: [ "staging", "production" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - uses: actions/upload-artifact@v4
      with:
        name: shopping-cart-api
        path: ${{ github.workspace }}/target/*

  release:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: shopping-cart-api

      - name: Release ${{ github.ref }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.sha }} # tag based on commit SHA
          release_name: Release ${{ github.ref }} # name based on branch
          prerelease: ${{ github.ref == 'staging' }}
